
name: Deploy to Firebase Hosting on PR
'on': 
  push:
    branches:
      - development

env:
  VITE_API_KEY: '${{ vars.VITE_API_KEY }}'
  VITE_AUTH_DOMAIN: '${{ vars.VITE_AUTH_DOMAIN }}'
  VITE_PROJECT_ID: '${{ vars.VITE_PROJECT_ID }}'
  VITE_STORAGE_BUCKET: '${{ vars.VITE_STORAGE_BUCKET }}'
  VITE_MESSAGING_SENDER_ID: '${{ vars.VITE_MESSAGING_SENDER_ID }}'
  VITE_APP_ID: '${{ vars.VITE_APP_ID }}'
  VITE_MEASUREMENT_ID: '${{ vars.VITE_MEASUREMENT_ID }}'      

jobs:
  build_and_preview:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CUSTOMRESETPASSWORD }}'
          projectId: customresetpassword
          target: custom-reset-password--dev
